; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Untitled:
.segment "CODE"

.segment "RODATA"


.export _music_data_untitled:=music_data_untitled

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env4,@env0 ; 00 : Instrument 1
	.word @env5,@env3,@env4,@env6 ; 01 : Instrument 2

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $d4,$cf,$db,$e2,$a8,$d3,$cb,$c0,$00,$07
@env4:
	.byte $7f,$00,$00
@env5:
	.byte $00,$cd,$ca,$c7,$c4,$c3,$c2,$c0,$00,$07
@env6:
	.byte $00,$cc,$a2,$d5,$a0,$c0,$9d,$e3,$bf,$00,$08

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80
@song0ref6:
	.byte $19, $a5, $20, $a5, $25, $a5, $28, $a5, $27, $a5, $1f, $a5, $2b, $a5, $00, $a5, $48, $19, $a5, $20, $a5, $25, $a5, $28
	.byte $a5, $27, $a5, $2f, $a5, $23, $a5, $00, $a5, $48
	.byte $41, $10
	.word @song0ref6
	.byte $48, $2c, $a5, $2b, $a5, $28, $a5, $27, $a5, $25, $a5, $27, $a5, $28, $a5, $27, $a5, $48, $00, $ff, $ff, $bd
@song0ref65:
	.byte $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf
	.byte $41, $0f
	.word @song0ref65
	.byte $48, $ff, $ff, $bf, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80
@song0ref97:
	.byte $27, $a5, $28, $a5, $2b, $a5, $2c, $a5, $2d, $a5, $2c, $a5, $2b, $a5, $28, $a5, $3b, $a5, $39, $a5, $38, $a5, $36, $a5
	.byte $38, $a5, $39, $a5, $3b, $a5, $39, $a5
	.byte $41, $10
	.word @song0ref97
	.byte $34, $a5, $33, $a5, $31, $a5, $2f, $a5, $2d, $a5, $2c, $a5, $2d, $a5, $2f, $a5
@song0ref148:
	.byte $00, $ff, $ff, $bd
@song0ref152:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0f
	.word @song0ref152
	.byte $ff, $ff, $bf, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80
@song0ref178:
	.byte $0d, $a5, $10, $a5, $0f, $a5, $13, $a5, $0d, $a5, $10, $a5, $0f, $a5, $08, $a5
	.byte $41, $10
	.word @song0ref178
	.byte $41, $10
	.word @song0ref178
	.byte $41, $10
	.word @song0ref178
	.byte $41, $13
	.word @song0ref148
	.byte $41, $0f
	.word @song0ref152
	.byte $ff, $ff, $bf, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $82, $40, $01
@song0ref219:
	.byte $a5, $17, $a5, $10, $a5, $19, $a5, $1f, $a5, $1a, $a5, $1f, $a5, $17
	.byte $41, $0e
	.word @song0ref219
	.byte $a5, $00
	.byte $41, $0e
	.word @song0ref219
	.byte $a5, $00
	.byte $41, $0e
	.word @song0ref219
	.byte $a5, $00, $a5
	.byte $41, $0f
	.word @song0ref152
	.byte $41, $0f
	.word @song0ref152
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $0f
	.word @song0ref152
	.byte $41, $0f
	.word @song0ref152
	.byte $41, $0f
	.word @song0ref152
	.byte $ff, $ff, $bf, $42
	.word @song0ch4loop
